# capitalai/output/markdown_writer.py
# CapitalAI Professional Audit Report Generator
# Designed for: (1) E-E-A-T Guardian review, (2) direct client delivery
# Tone: Professional, confident, client-first. Never salesy.

from datetime import datetime
from pathlib import Path


# ─────────────────────────────────────────────────────────────────────────────
# Score → visual helpers
# ─────────────────────────────────────────────────────────────────────────────

def _score_bar(score, out_of=10) -> str:
    """Turn a numeric score into a visual progress bar."""
    try:
        s = float(score)
    except (TypeError, ValueError):
        return "N/A"
    filled = round(s)
    empty  = out_of - filled
    bar    = "█" * filled + "░" * empty
    return f"`{bar}` {s}/{out_of}"


def _eeat_badge(score) -> str:
    try:
        s = float(score)
    except (TypeError, ValueError):
        return "⬜ N/A"
    if s >= 7.5: return "🟢 Strong"
    if s >= 5.0: return "🟡 Moderate"
    return "🔴 Weak"


def _priority_tag(score) -> str:
    try:
        s = float(score)
    except (TypeError, ValueError):
        return ""
    if s < 4.0: return " 🚨 **CRITICAL**"
    if s < 6.0: return " ⚠️ **HIGH PRIORITY**"
    return " ✅ Acceptable"


def _clean_excerpt(text: str, max_words: int = 40) -> str:
    """Return a clean, sentence-trimmed excerpt."""
    if not text:
        return ""
    words = text.split()
    if len(words) <= max_words:
        return text.strip()
    truncated = " ".join(words[:max_words])
    # Try to end on a sentence boundary
    for punct in [". ", "! ", "? "]:
        idx = truncated.rfind(punct)
        if idx > max_words * 3:  # At least half the excerpt
            return truncated[:idx + 1].strip()
    return truncated.strip() + "…"


def _get_page_excerpt(page: dict, max_words: int = 40) -> str:
    """Extract a meaningful excerpt from page body text."""
    body = page.get("body_excerpt", "") or page.get("full_text", "")
    return _clean_excerpt(body, max_words)


def _severity_emoji(count: int) -> str:
    if count == 0: return "✅"
    if count <= 2: return "⚠️"
    return "🔴"


# ─────────────────────────────────────────────────────────────────────────────
# Public entry point
# ─────────────────────────────────────────────────────────────────────────────

def write_markdown_report(
    domain: str,
    client_data: dict,
    competitor_data: dict,
    gap_results: dict,
    eeat_scores: dict,
    technical: dict,
    output_dir: str = "reports",
) -> str:
    timestamp  = datetime.now().strftime("%Y%m%d_%H%M")
    safe_domain = domain.replace(".", "_").replace("/", "_")
    filepath   = Path(output_dir) / f"{safe_domain}_{timestamp}_audit.md"
    filepath.parent.mkdir(parents=True, exist_ok=True)

    sections = []
    sections += _section_header(domain)
    sections += _section_executive_summary(domain, client_data, competitor_data, eeat_scores, technical)
    sections += _section_eeat(eeat_scores, client_data)
    sections += _section_content_gaps(gap_results, client_data, competitor_data)
    sections += _section_technical(technical, client_data)
    sections += _section_next_steps(eeat_scores, gap_results, technical)
    sections += _section_footer()

    filepath.write_text("\n".join(sections), encoding="utf-8")
    return str(filepath)


# ─────────────────────────────────────────────────────────────────────────────
# Section builders
# ─────────────────────────────────────────────────────────────────────────────

def _section_header(domain: str) -> list:
    now = datetime.now().strftime("%B %d, %Y")
    return [
        f"# 🔍 SEO Audit Report — `{domain}`",
        "",
        f"> **Prepared by:** CapitalAI — Ottawa's Self-Hosted AI SEO Agency  ",
        f"> **Date:** {now}  ",
        f"> **Powered by:** Crawl4AI + Ollama llama3.1:8b (100% local, zero cloud)  ",
        f"> **Confidential** — prepared exclusively for `{domain}`",
        "",
        "---",
        "",
        "> ### ⚠️ Human Review Gate",
        "> This report was generated by the CapitalAI autonomous audit engine.",
        "> **All findings, scores, and recommendations must be reviewed and approved",
        "> by the E-E-A-T Guardian before delivery to the client.**",
        "> Do not share this report externally before sign-off.",
        "",
        "---",
        "",
    ]


def _section_executive_summary(domain, client_data, competitor_data, eeat_scores, technical) -> list:
    agg       = eeat_scores.get("site_aggregate", {})
    tech      = technical.get("summary", {})
    overall   = agg.get("overall_score", "N/A")
    rating    = agg.get("rating", "N/A")
    verdict   = agg.get("verdict", "")
    n_pages   = len(client_data)
    n_comps   = len(competitor_data)
    n_gaps    = tech.get("missing_meta", 0) + tech.get("h1_issues", 0) + tech.get("no_schema_pages", 0)

    # Compute health colour
    try:
        o = float(overall)
        health = "🟢 Good" if o >= 7.5 else ("🟡 Needs Work" if o >= 5.0 else "🔴 Needs Immediate Attention")
    except (TypeError, ValueError):
        health = "⬜ Not Scored"

    lines = [
        "## 📋 Executive Summary",
        "",
        f"We audited **{n_pages} pages** on `{domain}`"
        + (f" and compared them against **{n_comps} competitor site(s)**." if n_comps else "."),
        "",
        "| 🏁 Overall Health | 🏆 E-E-A-T Score | 🔧 Technical Issues | 🕵️ Competitors Analyzed |",
        "|-------------------|-----------------|---------------------|------------------------|",
        f"| {health} | {_eeat_badge(overall)} {overall}/10 | {n_gaps} issues found | {n_comps} sites |",
        "",
    ]

    if verdict:
        lines += [
            f"> **Bottom line:** {verdict}",
            "",
        ]

    # Highlight the single most important finding
    page_scores = eeat_scores.get("page_scores", {})
    worst = None
    worst_score = 10.0
    for url, s in page_scores.items():
        if "parse_error" not in s:
            try:
                sc = float(s.get("overall_score", 10))
                if sc < worst_score:
                    worst_score = sc
                    worst = (url, s)
            except (TypeError, ValueError):
                pass

    if worst:
        url, s = worst
        lines += [
            "### 🎯 Most Critical Finding",
            "",
            f"The page at `{url}` scored **{worst_score}/10** on E-E-A-T — "
            f"the lowest on the site.",
            f"**Primary issue:** {s.get('top_issue', 'N/A')}",
            f"**Recommended fix:** {s.get('quick_fix', 'N/A')}",
            "",
        ]

    lines += ["---", ""]
    return lines


def _section_eeat(eeat_scores: dict, client_data: dict) -> list:
    agg         = eeat_scores.get("site_aggregate", {})
    page_scores = eeat_scores.get("page_scores", {})

    lines = [
        "## 🏆 E-E-A-T Audit",
        "",
        "_Google's E-E-A-T framework (Experience, Expertise, Authoritativeness, Trustworthiness) "
        "is the primary lens through which Google evaluates content quality. "
        "Low E-E-A-T is the #1 cause of ranking suppression under the Helpful Content system._",
        "",
    ]

    if not agg or "error" in agg:
        lines += ["> E-E-A-T scoring was skipped for this run. Re-run without `--skip-eeat`.", "", "---", ""]
        return lines

    # ── Site-level scorecard ────────────────────────────────────────────────
    lines += [
        "### Site-Level Scorecard",
        "",
        f"| Dimension | Score | Visual | What It Means |",
        f"|-----------|-------|--------|---------------|",
        f"| 🧪 Experience | {agg.get('experience','?')}/10 | {_score_bar(agg.get('experience',0))} | Real first-hand experience signals |",
        f"| 🎓 Expertise | {agg.get('expertise','?')}/10 | {_score_bar(agg.get('expertise',0))} | Subject-matter depth and accuracy |",
        f"| 🏛️ Authoritativeness | {agg.get('authoritativeness','?')}/10 | {_score_bar(agg.get('authoritativeness',0))} | Author bios, citations, brand signals |",
        f"| 🔒 Trustworthiness | {agg.get('trustworthiness','?')}/10 | {_score_bar(agg.get('trustworthiness',0))} | Contact info, privacy policy, HTTPS |",
        f"| **⭐ Overall** | **{agg.get('overall_score','?')}/10** | {_score_bar(agg.get('overall_score',0))} | **Composite E-E-A-T health** |",
        "",
        f"**Site Rating:** {agg.get('rating','N/A')}  ",
        f"**Verdict:** {agg.get('verdict','')}",
        "",
    ]

    # ── What each score means practically ──────────────────────────────────
    lines += [
        "<details>",
        "<summary>📖 How to interpret these scores</summary>",
        "",
        "- **8–10:** Google will likely reward this page with authority. Protect and amplify.",
        "- **5–7:** Competitively vulnerable. Improvement will directly impact rankings.",
        "- **0–4:** High risk. This page may be suppressed under Helpful Content updates.",
        "",
        "</details>",
        "",
    ]

    # ── Page-level breakdown ────────────────────────────────────────────────
    if not page_scores:
        lines += ["", "---", ""]
        return lines

    # Separate strong vs weak pages
    strong_pages  = [(u, s) for u, s in page_scores.items()
                     if "parse_error" not in s and float(s.get("overall_score", 0) or 0) >= 6.0]
    weak_pages    = [(u, s) for u, s in page_scores.items()
                     if "parse_error" not in s and float(s.get("overall_score", 10) or 10) < 6.0]
    weak_pages.sort(key=lambda x: float(x[1].get("overall_score", 10) or 10))

    # ── Weak pages (with content excerpts) ─────────────────────────────────
    if weak_pages:
        lines += [
            "### 🚨 Pages Needing Immediate Attention",
            "",
            "_These pages are dragging down your site's overall E-E-A-T signal. "
            "Each one is a ranking liability until fixed._",
            "",
        ]
        for url, scores in weak_pages[:8]:
            page      = client_data.get(url, {})
            excerpt   = _get_page_excerpt(page, max_words=35)
            score_val = scores.get("overall_score", "?")
            issue     = scores.get("top_issue", "N/A")
            fix       = scores.get("quick_fix", "N/A")

            lines += [
                f"#### {_priority_tag(score_val)} `{url}`",
                "",
                f"| Metric | Value |",
                f"|--------|-------|",
                f"| E-E-A-T Score | {_score_bar(score_val)} |",
                f"| Word Count | {page.get('word_count', '?')} words |",
                f"| Schema Markup | {'✅ ' + ', '.join(page.get('schema_types', [])) if page.get('schema_types') else '❌ None'} |",
                "",
            ]

            if excerpt:
                lines += [
                    f"**Current content (excerpt):**",
                    f"> _{excerpt}_",
                    "",
                    f"**Why this is a problem:** {issue}",
                    "",
                ]
            else:
                lines += [f"**Top Issue:** {issue}", ""]

            lines += [
                f"**✏️ Recommended fix:** {fix}",
                "",
                "---",
                "",
            ]

    # ── Strong pages ────────────────────────────────────────────────────────
    if strong_pages:
        lines += [
            "### ✅ Strong Pages — Protect & Amplify",
            "",
            "_These pages already demonstrate solid E-E-A-T signals. "
            "Internal linking from these pages to weaker ones will distribute authority._",
            "",
        ]
        for url, scores in strong_pages[:5]:
            page    = client_data.get(url, {})
            excerpt = _get_page_excerpt(page, max_words=30)
            lines += [
                f"**`{url}`** — Score: {_score_bar(scores.get('overall_score', 0))}",
            ]
            if excerpt:
                lines += [f"> _{excerpt}_", ""]
            else:
                lines.append("")

    lines += ["", "---", ""]
    return lines


def _section_content_gaps(gap_results: dict, client_data: dict, competitor_data: dict) -> list:
    gaps      = gap_results.get("content_gaps", [])
    opps      = gap_results.get("content_opportunities", [])
    strengths = gap_results.get("unique_strengths", [])

    lines = [
        "## 🗺️ Content Gap Analysis",
        "",
    ]

    if gap_results.get("note") == "No competitor data.":
        lines += [
            "> _No competitor URLs were provided for this audit. "
            "Re-run with `--competitors` to unlock full gap analysis._",
            "",
            "---",
            "",
        ]
        return lines

    lines += [
        f"We identified **{len(gaps)} topic gaps** where competitors are capturing traffic "
        f"that `{list(client_data.keys())[0].split('/')[2] if client_data else 'your site'}` "
        f"currently misses.",
        "",
    ]

    # ── Content gaps ────────────────────────────────────────────────────────
    if gaps:
        lines += [
            "### 🕳️ Topics Your Competitors Cover — You Don't",
            "",
            "_Each gap below is a keyword cluster where a competitor ranks and you don't. "
            "Each one represents lost organic traffic._",
            "",
        ]
        for i, g in enumerate(gaps[:15], 1):
            lines.append(f"**{i}.** {g}")
        lines.append("")

    # ── Content opportunities with suggested openings ───────────────────────
    if opps:
        lines += [
            "### 🎯 Top Content Opportunities",
            "",
            "_These are the highest-ROI pages to create first, based on gap severity and search intent._",
            "",
        ]
        for i, opp in enumerate(opps[:5], 1):
            # Generate a suggested title and opening from the opportunity string
            suggested_title = opp.strip().rstrip(".")
            lines += [
                f"#### Opportunity {i}: {suggested_title}",
                "",
                f"**Why it matters:** This topic gap is directly covered by competitors "
                f"and represents an unmet search intent for your target audience.",
                "",
                f"**Suggested page title:** _{suggested_title}_",
                "",
                f"**Sample opening paragraph:**",
                f"> _If you're looking for [topic], you've landed in the right place. "
                f"In this guide, we cover everything you need to know — from the basics "
                f"to advanced strategies that Ottawa businesses are using right now to [outcome]._",
                "",
                f"**Next action:** Assign to content writer. Target 1,200+ words. "
                f"Include LocalBusiness or Article schema.",
                "",
            ]

    # ── Unique strengths ────────────────────────────────────────────────────
    if strengths:
        lines += [
            "### 💪 Your Competitive Advantages",
            "",
            "_These are topics where you have unique coverage. "
            "Double down here — internal links, updated content, schema markup._",
            "",
        ]
        for s in strengths[:8]:
            lines.append(f"- **{s}**")
        lines.append("")

    # ── Competitor snapshot ─────────────────────────────────────────────────
    if competitor_data:
        lines += [
            "### 🏁 Competitor Snapshot",
            "",
            "| Competitor | Pages Crawled |",
            "|------------|---------------|",
        ]
        for comp_url, pages in competitor_data.items():
            lines.append(f"| `{comp_url}` | {len(pages)} pages |")
        lines.append("")

    lines += ["---", ""]
    return lines


def _section_technical(technical: dict, client_data: dict) -> list:
    tech   = technical.get("summary", {})
    schema = technical.get("schema_opportunities", [])

    missing_meta  = tech.get("missing_meta", 0)
    h1_issues     = tech.get("h1_issues", 0)
    alt_issues    = tech.get("alt_tag_issues", 0)
    no_schema     = tech.get("no_schema_pages", 0)
    thin_pages    = tech.get("thin_pages", 0)
    no_canonical  = tech.get("missing_canonical", 0)
    total         = tech.get("total_pages", len(client_data))

    total_issues = missing_meta + h1_issues + no_schema

    lines = [
        "## ⚙️ Technical SEO Health Check",
        "",
        f"_Scanned {total} pages. Found **{total_issues} high-priority technical issues** "
        f"that directly impact crawlability and ranking potential._",
        "",
        "### Issue Summary",
        "",
        "| Issue | Count | Severity | Impact |",
        "|-------|-------|----------|--------|",
        f"| {_severity_emoji(missing_meta)} Missing meta descriptions | **{missing_meta}** | {'High' if missing_meta > 0 else 'None'} | Hurts CTR in search results |",
        f"| {_severity_emoji(h1_issues)} H1 tag issues | **{h1_issues}** | {'High' if h1_issues > 0 else 'None'} | Confuses crawlers on page topic |",
        f"| {_severity_emoji(alt_issues)} Images missing alt text | **{alt_issues}** | {'Medium' if alt_issues > 0 else 'None'} | Accessibility + image search loss |",
        f"| {_severity_emoji(no_schema)} Pages without schema markup | **{no_schema}** | {'High' if no_schema > 0 else 'None'} | Missing rich result eligibility |",
        f"| {_severity_emoji(thin_pages)} Thin content pages (<300 words) | **{thin_pages}** | {'Medium' if thin_pages > 0 else 'None'} | E-E-A-T risk under Helpful Content |",
        f"| {_severity_emoji(no_canonical)} Missing canonical tags | **{no_canonical}** | {'Medium' if no_canonical > 0 else 'None'} | Duplicate content risk |",
        "",
    ]

    # ── Schema opportunities ────────────────────────────────────────────────
    if schema:
        lines += [
            "### 🏷️ Schema Markup Opportunities",
            "",
            "_Schema markup enables rich results in Google (star ratings, FAQs, breadcrumbs). "
            "Every page below is currently invisible to these features._",
            "",
        ]
        for opp in schema:
            url    = opp.get("url", "")
            schema_type = opp.get("priority_schema", "?")
            reason = opp.get("reason", "")
            page   = client_data.get(url, {})
            title  = page.get("title", url)
            lines += [
                f"**Page:** `{url}`  ",
                f"**Title:** _{title}_  ",
                f"**Add:** `{schema_type}` schema  ",
                f"**Why:** {reason}",
                "",
            ]

    # ── Page-level technical details ────────────────────────────────────────
    missing_meta_urls = technical.get("missing_meta_description", [])
    no_schema_urls    = technical.get("no_schema", [])
    thin_urls         = technical.get("thin_content", [])

    if missing_meta_urls:
        lines += [
            "### 📝 Pages Missing Meta Descriptions",
            "",
            "_Meta descriptions are your ad copy in Google search results. "
            "Missing ones mean Google writes them for you — usually poorly._",
            "",
        ]
        for url in missing_meta_urls[:10]:
            page    = client_data.get(url, {})
            excerpt = _get_page_excerpt(page, max_words=20)
            lines += [
                f"- **`{url}`**",
            ]
            if excerpt:
                lines += [f"  _Current content hint: \"{excerpt}\"_"]
        lines.append("")

    if thin_urls:
        lines += [
            "### 📄 Thin Content Pages",
            "",
            "_Pages under 300 words are at direct risk of demotion under Google's "
            "Helpful Content system. Each needs expansion or consolidation._",
            "",
            "| Page | Word Count | Recommendation |",
            "|------|-----------|----------------|",
        ]
        for item in thin_urls[:10]:
            url = item.get("url", "")
            wc  = item.get("word_count", 0)
            rec = "Expand to 800+ words" if wc > 100 else "Consolidate or noindex"
            lines.append(f"| `{url}` | {wc} words | {rec} |")
        lines.append("")

    lines += ["---", ""]
    return lines


def _section_next_steps(eeat_scores: dict, gap_results: dict, technical: dict) -> list:
    tech         = technical.get("summary", {})
    missing_meta = tech.get("missing_meta", 0)
    h1_issues    = tech.get("h1_issues", 0)
    no_schema    = tech.get("no_schema_pages", 0)
    thin_pages   = tech.get("thin_pages", 0)
    gaps         = gap_results.get("content_gaps", [])
    opps         = gap_results.get("content_opportunities", [])

    page_scores  = eeat_scores.get("page_scores", {})
    critical_count = sum(
        1 for s in page_scores.values()
        if "parse_error" not in s and float(s.get("overall_score", 10) or 10) < 5.0
    )

    lines = [
        "## 🚦 Prioritized Action Plan",
        "",
        "_Tasks are ordered by ROI impact. Complete in sequence for maximum compounding effect._",
        "",
        "---",
        "",
        "### 🔴 Week 1 — Fix the Foundation (Stop the Bleeding)",
        "",
    ]

    week1 = []
    if missing_meta > 0:
        week1.append(f"- [ ] **Write meta descriptions** for {missing_meta} page(s) — "
                     f"direct CTR impact, 30-minute fix per page")
    if h1_issues > 0:
        week1.append(f"- [ ] **Fix H1 tags** on {h1_issues} page(s) — "
                     f"critical for crawler topic understanding")
    if critical_count > 0:
        week1.append(f"- [ ] **Emergency E-E-A-T repair** on {critical_count} critical page(s) — "
                     f"add author bio, trust signals, and at least one verifiable source")
    if not week1:
        week1.append("- [ ] ✅ No critical Week 1 items — move to Month 1 tasks")

    lines += week1
    lines += [
        "",
        "### 🟡 Month 1 — Build Authority",
        "",
        f"- [ ] **Add schema markup** to {no_schema} unstructured page(s) — "
        f"unlock rich result eligibility in Google",
        f"- [ ] **Expand thin content** on {thin_pages} page(s) to 800+ words with original insights",
        "- [ ] **Add author bio block** to all content pages — single highest-ROI E-E-A-T fix",
        "- [ ] **Internal link audit** — connect strong E-E-A-T pages to weak ones",
        "- [ ] **Add FAQ schema** to any service or product pages",
        "",
        "### 🟢 Month 2–3 — Scale & Dominate",
        "",
    ]

    month3 = []
    if opps:
        month3.append(f"- [ ] **Create {min(len(opps), 5)} new pillar pages** from content opportunities identified above")
    if gaps:
        month3.append(f"- [ ] **Close {len(gaps)} content gaps** — assign each to a writer with brief + schema requirements")
    month3 += [
        "- [ ] **Geo-programmatic expansion** — replicate top pages for Ottawa neighbourhood + NCR service areas",
        "- [ ] **Weekly freshness automation** — update content timestamps + add new data points via n8n",
        "- [ ] **AI citation targeting** — restructure top pages as answer capsules for Perplexity, ChatGPT, Claude",
    ]
    lines += month3
    lines += ["", "---", ""]
    return lines


def _section_footer() -> list:
    now = datetime.now().strftime("%B %d, %Y at %H:%M")
    return [
        "## 📌 About This Report",
        "",
        "| Detail | Value |",
        "|--------|-------|",
        f"| Generated | {now} |",
        "| Engine | CapitalAI-Audit-Crawler v1.0 |",
        "| Crawler | Crawl4AI (Playwright-based, JS rendering) |",
        "| AI Model | Ollama llama3.1:8b (100% local, zero cloud) |",
        "| Privacy | No client data left your machine |",
        "",
        "---",
        "",
        "> ### ⚠️ Final Human Review Required",
        "> **This report must be reviewed and approved by the CapitalAI E-E-A-T Guardian**",
        "> before sharing with any client.",
        "> All AI-generated scores, excerpts, and recommendations require human verification.",
        "> If any finding seems incorrect, escalate immediately — never deliver unchecked.",
        "",
        "---",
        "",
        "*CapitalAI.ca — Ottawa's Self-Hosted AI SEO Agency*  ",
        "*Privacy-first. Results-focused. No black boxes.*",
    ]
